#pragma once

#include "BaseEvent.h"

/* CoreEvents.h
	This header contains definitions for all core Event classes, as well as the CategoryID and TypeID
	enums.  Include this file to access core Events.

	The enums and classes are generated by the preprocessor by defining the macros in CoreEvents_TypeList.h
	and CoreEvents_CategoryList.h multiple times.  Don't modify this file to create new Event types or 
	category types.  Instead, add the type or category to those files.
*/

namespace Enterprise::Event
{
	#include "Generation\StartEnums.h"
	namespace TypeIDs {
		enum {
			None = 0,
			#include "CoreEvents_TypeList.h"
			NumOfCoreTypes
		};
	}
	namespace CategoryIDs {
		enum {
			All = 0,
			#include "CoreEvents_CategoryList.h"
			NumOfCoreCategories
		};
	}
	#include "Generation\EndEnums.h"

	// The three includes below expand into all the core Event classes.
	#include "Generation/StartClasses.h"
	#include "CoreEvents_TypeList.h"
	#include "Generation\EndClasses.h"
}