#pragma once
#include "Enterprise/Events/Events.h"

using Enterprise::Events;

namespace EventCategories
{
/// Events generated by the game window.
extern const Events::EventCategory Window;
}

namespace EventTypes
{
// Application Events

/// The user has attempted to quit the game from the OS.
extern const Events::EventType QuitRequested;

// Window Events

/// The user has tried to close the game window.
extern const Events::EventType WindowClose;
/// The game window has moved. | std::pair(int posX, int posY)
extern const Events::EventType WindowMove;
/// The game window has been resized. | std::pair(int width, int height)
extern const Events::EventType WindowResize;
/// The game window has gained focus.
extern const Events::EventType WindowFocus;
/// The game window has lost focus.
extern const Events::EventType WindowLostFocus;

}
